---
- name: Настройка балансировщика нагрузки Nginx
  hosts: load_balancer
  become: yes
  tasks:
    - name: Установить Nginx
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: Включить Nginx в автозагрузку
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Создать конфигурационный файл Nginx для балансировщика
      template:
        src: templates/nginx_load_balancer.conf.j2
        dest: /etc/nginx/conf.d/balancer.conf

    - name: Проверить конфигурацию Nginx
      command: nginx -t
      register: nginx_test
      ignore_errors: yes

    - name: Показать результат проверки Nginx конфигурации
      debug:
        var: nginx_test.stdout_lines

    - name: Перезапустить Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes